### ISSUE TITLE
Crashes Cura on new Thingiverse

### ISSUE THREAD

**Issue by dxgldotorg** [ChrisTerBeke/ThingiBrowser#20]
Attempting to open the ThingiBrowser plugin since the Thingiverse update causes the following error:

`Traceback (most recent call last):
  File "C:\Users\William\AppData\Roaming\cura\4.5\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseApiClient.py", line 135, in parse
    on_finished(result)
  File "C:\Users\William\AppData\Roaming\cura\4.5\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseService.py", line 326, in _onQueryFinished
    self._things.extend(things)
TypeError: 'JSONObject' object is not iterable
`

**Comment by ChrisTerBeke** [comment]
Probably related to https://github.com/ChrisTerBeke/ThingiBrowser/issues/16. Which version of the plugin are you using?

**Comment by Riwithiy** [comment]
Same here, running plugin version 1.5.0 and cura 4.5.0


Error traceback:
Traceback (most recent call last):
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseApiClient.py", line 135, in parse
    on_finished(result)
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseService.py", line 326, in _onQueryFinished
    self._things.extend(things)
TypeError: 'JSONObject' object is not iterable



log:

Thread 0x00002c3c (most recent call first):
  File "C:\Program Files\Ultimaker Cura 4.5\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00005320 (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf\__init__.py", line 2117 in wait
  File "zeroconf\__init__.py", line 1434 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000257c (most recent call first):
  File "threading.py", line 297 in wait
  File "threading.py", line 549 in wait
  File "C:\Program Files\Ultimaker Cura 4.5\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 74 in _handleOnServiceChangedRequests
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000011e0 (most recent call first):
  File "threading.py", line 297 in wait
  File "zeroconf\__init__.py", line 2117 in wait
  File "zeroconf\__init__.py", line 1262 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000076c (most recent call first):
  File "zeroconf\__init__.py", line 1183 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000537c (most recent call first):
  File "ntpath.py", line 249 in islink
  File "serial\tools\list_ports_common.py", line 48 in __init__
  File "serial\tools\list_ports_windows.py", line 209 in iterate_comports
  File "serial\tools\list_ports_windows.py", line 299 in comports
  File "C:\Program Files\Ultimaker Cura 4.5\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 112 in getSerialPortList
  File "C:\Program Files\Ultimaker Cura 4.5\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 84 in _updateThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000005c8 (most recent call first):
  File "threading.py", line 297 in wait
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2163 in wait
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1464 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000032bc (most recent call first):
  File "threading.py", line 297 in wait
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2163 in wait
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1283 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000001fc (most recent call first):
  File "C:\Users\janvb\AppData\Roaming\cura\4.5\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1204 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00002a78 (most recent call first):
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 152 in _storeStderrToLogThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00003fd4 (most recent call first):
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 140 in _storeOutputToLogThread
  File "threading.py", line 862 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00005228 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00005260 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001ad4 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x000052c8 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00001ed4 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000208c (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x00005238 (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Thread 0x0000501c (most recent call first):
  File "threading.py", line 293 in wait
  File "threading.py", line 424 in acquire
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
  File "threading.py", line 914 in _bootstrap_inner
  File "threading.py", line 882 in _bootstrap

Current thread 0x00004300 (most recent call first):
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 380 in _logInfoWidget
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 180 in _createDialog
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 86 in __init__
  File "X:\4.5-exe\build\inst\bin\cura_app.py", line 150 in exceptHook
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 370 in exec_
  File "X:\4.5-exe\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 823 in run
  File "X:\4.5-exe\build\inst\bin\cura_app.py", line 214 in <module>
  File "Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load
  File "__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 957 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 968 in _find_and_load

**Comment by dxgldotorg** [comment]
Installed ThingiBrowser 1.5.1 from GitHub as it is not yet uploaded to the Cura Marketplace.
Now it works again.

**Comment by Riwithiy** [comment]
ok nice will try that thx

**Comment by ChrisTerBeke** [comment]
It’s uploaded but pending review by Ultimaker. Good to hear that it fixes your issue (which means it was caused by #16).
