### ISSUE TITLE
Crashes Cura when Thingiverse is down for maintenance.

### ISSUE THREAD

**Issue by Xyphurr** [ChrisTerBeke/ThingiBrowser#6]
**Cura Version:** 4.1.0
**ThingiBrowser version:** 1.1.2 (Found in plugins.json due to being unable to open Cura)
**Platform:** Windows-10-10.0.17134
**QT version:** 5.10.0
**PyQt version:** 5.10
**OpenGL:** Not yet initialized

Caused by attempting to start Cura while Thingiverse is down for maintenance, as seen here:
![image](https://user-images.githubusercontent.com/10656350/62002346-1f2c2000-b0b7-11e9-8b55-bcac38ad9e5c.png)

![image](https://user-images.githubusercontent.com/10656350/62002350-32d78680-b0b7-11e9-801c-9090afd7bd6c.png)

Error traceback is as follows:
```
Traceback (most recent call last):
  File "C:\Users\*username*\AppData\Roaming\cura\4.1\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseApiClient.py", line 136, in parse
    return on_failed(JSONObject(response))
  File "C:\Users\*username*\AppData\Roaming\cura\4.1\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseService.py", line 175, in _onRequestFailed
    mb.setText("Thingiverse return an error: {}.".format(error.error if error else "Unknown"))
AttributeError: 'JSONObject' object has no attribute 'error'
```

Cura starts as expected if I manually remove the ThingiBrowser plugin from the Cura plugins folder, narrowing the crash down to this plugin.

**Comment by kscr-rocket** [comment]
more detailed trace:

`
2019-08-01 11:18:41,186 - WARNING - [MainThread] ThingiBrowser.thingiverse.ThingiverseApiClient.parse [135]: API returned status code 503: None
2019-08-01 11:18:41,454 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [61]: An uncaught error has occurred!
2019-08-01 11:18:41,460 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: Traceback (most recent call last):
2019-08-01 11:18:41,464 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "C:\Users\Kai Schröder\AppData\Roaming\cura\4.2\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseApiClient.py", line 136, in parse
2019-08-01 11:18:41,468 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:     return on_failed(JSONObject(response))
2019-08-01 11:18:41,471 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "C:\Users\Kai Schröder\AppData\Roaming\cura\4.2\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseService.py", line 175, in _onRequestFailed
2019-08-01 11:18:41,475 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:     mb.setText("Thingiverse return an error: {}.".format(error.error if error else "Unknown"))
2019-08-01 11:18:41,479 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: AttributeError: 'JSONObject' object has no attribute 'error'
`

**Comment by CyberBLN** [comment]
more detailed trace:

`
2019-08-01 11:18:41,186 - WARNING - [MainThread] ThingiBrowser.thingiverse.ThingiverseApiClient.parse [135]: API returned status code 503: None
2019-08-01 11:18:41,454 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [61]: An uncaught error has occurred!
2019-08-01 11:18:41,460 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: Traceback (most recent call last):
2019-08-01 11:18:41,464 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "C:\Users\Kai Schröder\AppData\Roaming\cura\4.2\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseApiClient.py", line 136, in parse
2019-08-01 11:18:41,468 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:     return on_failed(JSONObject(response))
2019-08-01 11:18:41,471 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:   File "C:\Users\Kai Schröder\AppData\Roaming\cura\4.2\plugins\ThingiBrowser\ThingiBrowser\thingiverse\ThingiverseService.py", line 175, in _onRequestFailed
2019-08-01 11:18:41,475 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]:     mb.setText("Thingiverse return an error: {}.".format(error.error if error else "Unknown"))
2019-08-01 11:18:41,479 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: AttributeError: 'JSONObject' object has no attribute 'error'
`
